SELECT 
    tc.TABLE_NAME,
    tc.CONSTRAINT_NAME,
    tc.CONSTRAINT_TYPE,
    cc.CHECK_CLAUSE
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
    LEFT JOIN INFORMATION_SCHEMA.CHECK_CONSTRAINTS AS cc
    ON tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME
WHERE 
    tc.TABLE_NAME = 'KhachHang' -- Change this name to the the table's name you wanna show.
ORDER BY 
    tc.CONSTRAINT_TYPE, 
    tc.CONSTRAINT_NAME;
