ALTER TABLE NhanVien
ADD CONSTRAINT FK_NV_ID_buttoan FOREIGN KEY (ID_buttoan) REFERENCES Ben_Nhan(ID_ben_nhan);

ALTER TABLE CongTyThucPham
ADD CONSTRAINT FK_CTTP_ID_buttoan FOREIGN KEY (ID_buttoan) REFERENCES Ben_Nhan(ID_ben_nhan);

ALTER TABLE CongTyVanChuyen
ADD CONSTRAINT FK_CTVC_ID_buttoan FOREIGN KEY (ID_buttoan) REFERENCES Ben_Nhan(ID_ben_nhan);

ALTER TABLE QuanLyCaLam
ADD CONSTRAINT FK_QLCL_IDcaLam FOREIGN KEY (ID_calam) REFERENCES CaLam(ID_calam);

ALTER TABLE QuanLyCaLam
ADD CONSTRAINT FK_QLCL_ID_NV FOREIGN KEY (ID_NhanVien) REFERENCES NhanVien(ID_NhanVien);

ALTER TABLE MonAn_TrongNgay
ADD CONSTRAINT FK_MATN_ID_MonAn FOREIGN KEY (ID_mon_an) REFERENCES MonAn(ID_mon_an);

ALTER TABLE ButToan
ADD CONSTRAINT FK_BT_ID_QL FOREIGN KEY (ID_quanly) REFERENCES NhanVien(ID_NhanVien);

ALTER TABLE ButToanThu
ADD CONSTRAINT FK_BTT_ID_ButToan FOREIGN KEY (ID_but_toan) REFERENCES ButToan(ID_but_toan);

ALTER TABLE ButToanThu
ADD CONSTRAINT FK_BTT_ID_DonHang FOREIGN KEY (ID_don_hang) REFERENCES DonHang(ID_don_hang);

ALTER TABLE ButToanChi
ADD CONSTRAINT FK_BTC_ID_ButToan FOREIGN KEY (ID_but_toan) REFERENCES ButToan(ID_but_toan);

ALTER TABLE ButToanChi
ADD CONSTRAINT FK_BTC_ID_ben_nhan FOREIGN KEY (ID_ben_nhan) REFERENCES Ben_Nhan(ID_ben_nhan);

ALTER TABLE DonHang
ADD CONSTRAINT FK_DH_ID_KH FOREIGN KEY (SDT_KhachHang) REFERENCES KhachHang(SDT_KhachHang);

ALTER TABLE DonHang
ADD CONSTRAINT FK_DH_ID_NV FOREIGN KEY (ID_NhanVien) REFERENCES NhanVien(ID_NhanVien);

ALTER TABLE DonHang_Taicho
ADD CONSTRAINT FK_DHTC_IDDHTC FOREIGN KEY (ID_don_hang) REFERENCES DonHang(ID_don_hang);

ALTER TABLE DonHang_Tructuyen
ADD CONSTRAINT FK_DHTT_IDDHTT FOREIGN KEY (ID_don_hang) REFERENCES DonHang(ID_don_hang);

ALTER TABLE DonHang_Tructuyen
ADD CONSTRAINT FK_DHTT_IDCTVC FOREIGN KEY (ID_congty) REFERENCES CongTyVanChuyen(ID_congty);

ALTER TABLE Quan_ly_mon_an_trong_DonHang
ADD CONSTRAINT FK_QLCMATDH_IDDH FOREIGN KEY (ID_don_hang) REFERENCES DonHang(ID_don_hang);

ALTER TABLE Quan_ly_mon_an_trong_DonHang
ADD CONSTRAINT FK_QLCMATDH_IDMAvN FOREIGN KEY (ID_mon_an,Ngay) REFERENCES MonAn_TrongNgay(ID_mon_an, Ngay);

ALTER TABLE Vi_pham
ADD CONSTRAINT FK_VP_IDNV FOREIGN KEY (ID_NhanVien) REFERENCES NhanVien(ID_NhanVien);





