ALTER TABLE NhanVien
DROP CONSTRAINT FK_NV_ID_buttoan;

ALTER TABLE CongTyThucPham
DROP CONSTRAINT FK_CTTP_ID_buttoan;

ALTER TABLE CongTyVanChuyen
DROP CONSTRAINT FK_CTVC_ID_buttoan;

ALTER TABLE QuanLyCaLam
DROP CONSTRAINT FK_QLCL_IDcaLam;

ALTER TABLE QuanLyCaLam
DROP CONSTRAINT FK_QLCL_ID_NV;

ALTER TABLE MonAn_TrongNgay
DROP CONSTRAINT FK_MATN_ID_MonAn;

ALTER TABLE ButToan
DROP CONSTRAINT FK_BT_ID_QL;

ALTER TABLE ButToanThu
DROP CONSTRAINT FK_BTT_ID_ButToan;

ALTER TABLE ButToanThu
DROP CONSTRAINT FK_BTT_ID_DonHang;

ALTER TABLE ButToanChi
DROP CONSTRAINT FK_BTC_ID_ButToan;

ALTER TABLE ButToanChi
DROP CONSTRAINT FK_BTC_ID_ben_nhan;

ALTER TABLE DonHang
DROP CONSTRAINT FK_DH_ID_KH;

ALTER TABLE DonHang
DROP CONSTRAINT FK_DH_ID_NV;

ALTER TABLE DonHang_Taicho
DROP CONSTRAINT FK_DHTC_IDDHTC;

ALTER TABLE DonHang_Tructuyen
DROP CONSTRAINT FK_DHTT_IDDHTT;

ALTER TABLE DonHang_Tructuyen
DROP CONSTRAINT FK_DHTT_IDCTVC;

ALTER TABLE Quan_ly_mon_an_trong_DonHang
DROP CONSTRAINT FK_QLCMATDH_IDDH;

ALTER TABLE Quan_ly_mon_an_trong_DonHang
DROP CONSTRAINT FK_QLCMATDH_IDMAvN;

ALTER TABLE Vi_pham
DROP CONSTRAINT FK_VP_IDNV;
